language: node_js
node_js:
  - '10'
cache: yarn
script:
  - yarn prepare
  - yarn pretest
  # - yarn build-storybook
after_success:
  - yarn build-storybook
deploy:
  provider: pages
  local_dir: example
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
