version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    docker:
      - image: circleci/node:latest
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run:
          name: Install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "yarn.lock" }}
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run:
          name: Install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: ESLint
          command: yarn lint
  workflows:
    version: 2
    build_and_test:
      jobs:
        - build
        - test:
            requires:
              - build
            filters:
              branches:
                ignore: gh-pages
